# Numpy Intro

In [1]:
import numpy as np

In [2]:
list1 = [10, 20, 30]
list1

[10, 20, 30]

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [5]:
type(list1)

list

In [6]:
type(arr1)

numpy.ndarray

In [26]:
arr2 = np.arange(10,21, 1)
arr2


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
list2 = [40, 30, 50]
list3 = [list1, list2]

In [12]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 30, 50]])

In [13]:
type(arr3)

numpy.ndarray

In [14]:
arr3.shape

(2, 3)

In [16]:
arr3dim = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
arr3dim

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3dim.shape

(2, 2, 3)

In [18]:
list1 * 3


[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [20]:
arr3dim * 3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[21, 24, 27],
        [30, 33, 36]]])

In [24]:
arr2 = np.array(list2)
arr2

array([40, 30, 50])

In [23]:
arr1*arr2

array([ 400,  600, 1500])

In [25]:
arr1*arr3dim


array([[[ 10,  40,  90],
        [ 40, 100, 180]],

       [[ 70, 160, 270],
        [100, 220, 360]]])

In [27]:
arr1 * arr2


ValueError: operands could not be broadcast together with shapes (3,) (11,) 

In [31]:
arr1d = np.arange(1, 13, 1)
arr1d.shape


(12,)

In [41]:
arr2d_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr2d = np.array(arr2d_list)
arr2d.shape

(3, 4)

In [42]:
arr3d_list = [[[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]], [[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4],[1, 2, 3, 4]]]
arr3d = np.array(arr3d_list)
arr3d.shape

(2, 5, 4)

In [43]:
arr3

array([[10, 20, 30],
       [40, 30, 50]])

In [44]:
arr3[1][2]

50

In [45]:
arr3[0]

array([10, 20, 30])

In [46]:
arr3[1][2]*2

100

In [47]:
arr3[0:2][1:2]

array([[40, 30, 50]])

In [48]:
arr3[::2][1:2]

array([], shape=(0, 3), dtype=int32)

In [50]:
arr3[:,2]

array([30, 50])

In [54]:
arr3.sum()
arr3

array([[10, 20, 30],
       [40, 30, 50]])

In [55]:
arr3.mean()
arr3

array([[10, 20, 30],
       [40, 30, 50]])

In [56]:
for x in arr3:
    print(x)

[10 20 30]
[40 30 50]


In [62]:
for x in arr3:
    for num in x:
        print(num)

10
20
30
40
30
50


In [64]:
for x in np.nditer(arr3):
    print(x)

10
20
30
40
30
50
